-- MySQL Script generated by MySQL Workbench
-- Sun May 21 01:30:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `c_id` INT NOT NULL,
  `c_time` DATETIME NULL,
  `star` INT NULL,
  `text` VARCHAR(45) NULL,
  `u_id` INT NOT NULL,
  `p_id` INT NOT NULL,
  PRIMARY KEY (`c_id`, `p_id`),
  INDEX `fk_Comment_User1_idx` (`u_id` ASC) VISIBLE,
  INDEX `fk_Comment_Product1_idx` (`p_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`u_id`)
    REFERENCES `mydb`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Product1`
    FOREIGN KEY (`p_id`)
    REFERENCES `mydb`.`Product` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discount_coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Discount_coupon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Discount_coupon` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discount_coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Discount_coupon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Discount_coupon` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Following`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Following` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Following` (
  `u_id` INT NOT NULL,
  `s_id` INT NOT NULL,
  PRIMARY KEY (`u_id`, `s_id`),
  INDEX `fk_Following_Shop1_idx` (`s_id` ASC) VISIBLE,
  CONSTRAINT `fk_Following_User`
    FOREIGN KEY (`u_id`)
    REFERENCES `mydb`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Following_Shop1`
    FOREIGN KEY (`s_id`)
    REFERENCES `mydb`.`Shop` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Free_shipping_coupon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Free_shipping_coupon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Free_shipping_coupon` (
  `Coupon_id` INT NOT NULL,
  `Coupon_state` ENUM('used', 'unused') NULL,
  `begin_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `u_id` INT NOT NULL,
  `Order_o_id` INT NOT NULL,
  `range` INT NULL,
  PRIMARY KEY (`Coupon_id`),
  INDEX `fk_Coupon_User1_idx` (`u_id` ASC) VISIBLE,
  INDEX `fk_Coupon_Order1_idx` (`Order_o_id` ASC) VISIBLE,
  CONSTRAINT `fk_Coupon_User10`
    FOREIGN KEY (`u_id`)
    REFERENCES `mydb`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coupon_Order10`
    FOREIGN KEY (`Order_o_id`)
    REFERENCES `mydb`.`Order` (`o_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LogisticsInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LogisticsInfo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LogisticsInfo` (
  `l_id` INT NOT NULL,
  `inc` VARCHAR(45) NULL,
  `l_state` ENUM('Collected', 'in transit', 'signed') NOT NULL,
  `expect_data` DATETIME NULL,
  `from` VARCHAR(45) NULL,
  `to` VARCHAR(45) NULL,
  PRIMARY KEY (`l_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `o_id` INT NOT NULL,
  `o_time` DATETIME NULL,
  `total_price` INT NULL,
  `u_id` INT NOT NULL,
  `s_id` INT NOT NULL,
  `l_id` INT NOT NULL,
  PRIMARY KEY (`o_id`),
  INDEX `fk_Order_User1_idx` (`u_id` ASC) VISIBLE,
  INDEX `fk_Order_Shop1_idx` (`s_id` ASC) VISIBLE,
  INDEX `fk_Order_LogisticsInfo1_idx` (`l_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`u_id`)
    REFERENCES `mydb`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Shop1`
    FOREIGN KEY (`s_id`)
    REFERENCES `mydb`.`Shop` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_LogisticsInfo1`
    FOREIGN KEY (`l_id`)
    REFERENCES `mydb`.`LogisticsInfo` (`l_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OrderItem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OrderItem` (
  `oi_id` INT NOT NULL,
  `amout` INT NULL,
  `Product_p_id` INT NOT NULL,
  `o_id` INT NOT NULL,
  PRIMARY KEY (`oi_id`, `o_id`),
  INDEX `fk_OrderItem_Product1_idx` (`Product_p_id` ASC) VISIBLE,
  INDEX `fk_OrderItem_Order1_idx` (`o_id` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItem_Product1`
    FOREIGN KEY (`Product_p_id`)
    REFERENCES `mydb`.`Product` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`o_id`)
    REFERENCES `mydb`.`Order` (`o_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `p_id` INT NOT NULL,
  `p_name` VARCHAR(45) NULL,
  `p_category` VARCHAR(45) NULL,
  `price` INT NULL,
  `imageURL` VARCHAR(45) NULL,
  `Shop_s_id` INT NOT NULL,
  PRIMARY KEY (`p_id`),
  INDEX `fk_Product_Shop1_idx` (`Shop_s_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Shop1`
    FOREIGN KEY (`Shop_s_id`)
    REFERENCES `mydb`.`Shop` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Shop` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Shop` (
  `s_id` INT NOT NULL,
  `s_name` VARCHAR(45) NULL,
  `s_tel` VARCHAR(45) NULL,
  `s_category` VARCHAR(45) NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `u_id` INT NOT NULL,
  `u_name` VARCHAR(45) NULL,
  `u_tel` VARCHAR(45) NULL,
  `u_address` VARCHAR(45) NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;

-- ---------------------------------------------------------
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS `course_work`.`Discount_coupon` (
  `Coupon_id` INT NOT NULL,
  `Coupon_state` ENUM('used', 'unused') NULL,
  `begin_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `u_id` INT NOT NULL,
  `Order_o_id` INT NOT NULL,
  `min_amount` INT NULL,
  `discount` INT NULL,
  PRIMARY KEY (`Coupon_id`),
  INDEX `fk_Coupon_User1_idx` (`u_id` ASC) VISIBLE,
  INDEX `fk_Coupon_Order1_idx` (`Order_o_id` ASC) VISIBLE,
  CONSTRAINT `fk_Coupon_User10`
    FOREIGN KEY (`u_id`)
    REFERENCES `course_work`.`User` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coupon_Order10`
    FOREIGN KEY (`Order_o_id`)
    REFERENCES `course_work`.`Order` (`o_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- ----------------------------------------------